### ISSUE TITLE
Deliver being deprecated 

### ISSUE THREAD

**Issue by adamantnz** [halogenandtoast/monban-generators#9]
Hey there - I noticed when working with the password_reset generator that password_reset_controller.rb is using #deliver which is being deprecated in rails 5. I think that by default this should be changed to using #deliver_now as per the below warning.

Just wanted to flag this in case this wasn't already on your radar.

``
DEPRECATION WARNING: #deliver is deprecated and will be removed in Rails 5. Use #deliver_now to deliver immediately or #deliver_later to deliver through Active Job. (called from create at   app/controllers/password_resets_controller.rb:12) ``

**Comment by halogenandtoast** [comment]
Merged into master.
